### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by lucapcf** [IDEjr/relab-jr#16]
### OBS.:
- Criar 1 componente que será chamado n vezes com argumentos para "campos *"

## Desktop

- [x] logo
- [ ] drop-down
- [x] links
- [ ] ícones links
- [x] formatação

## Mobile

- [x] logo
- [x] hamburguer
- [x] links
- [ ] ícones links
- [ ] formatação

**Comment by BrunoCosta04** [comment]
Some styling ajustments to do and the dropdown menu to, maybe we could se if its actually needed.
